# vim: ts=2 sw=2 et

name: Update Groups.io
on:
  push:
    branches:
      - master
    paths:
      - 'groups/*.yml' # These are the paths which are watched for changes

jobs:
  generate_directory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install requests pyyaml
    - name: Update Groups.io
      env:
        GROUPSIO_USERNAME: ${{ secrets.GROUPSIO_USERNAME }}
        GROUPSIO_PASSWORD: ${{ secrets.GROUPSIO_PASSWORD }}
        CONFIG_DIR: 'groups/assets'
      run: python .github/workflows/sync-yaml-to-groupsio.py -g

